name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Pull YAML data
        run: ./tools/sync_data.sh
      - name: Build and Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          install_command: npm install,
          build_command: npm run build,
          build_directory: public
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy staging from commit ${{ github.sha }}"
      - name: Commit built files
        run: |
          git log -1
          git branch
          git status
          ls -l src/contents
          ls -l public
          git add -f public
          git status
      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release
          commit_message: 'Sync data from Google Sheets'
          file_pattern: src/contents/*.yaml
